In [11]:
%matplotlib inline
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [12]:
def read_data(sbj_i, srs_i):
    x = pd.read_csv('/Users/shanmvas/Downloads/grasp-and-lift-eeg-detection/train/subj{}_series{}_data.csv'  .format(sbj_i, srs_i), index_col='id')
    y = pd.read_csv('/Users/shanmvas/Downloads/grasp-and-lift-eeg-detection/train/subj{}_series{}_events.csv'.format(sbj_i, srs_i), index_col='id')
    return x,y

def read_all_data():
    print('Reading data...'),
    data = [read_data(i,j) for j in range(1,2) for i in range(1,2)]
    print('Data read. There are {} series in total.'.format(len(data)))
    return data


## Standardization

def standardize_data(data):
    print('Standardizing data...'),
    scaler = StandardScaler()

    all_x = pd.DataFrame()
    for x,_ in data:
        all_x = pd.concat((x, all_x))

    scaler.fit(all_x)
    data_std = []
    for x,y in data:
        data_std.append([scaler.transform(x),y])
        
    print('Data standardized.')
    return data_std


## Separate Training and Validation data

def split_train_valid(data):
    print('Separating data into train/valid...'),
    train = data
    # We arbitrarily pick one series from each subject to be part of the validation set.
    valid_idxs = reversed([0,14,23,25,37,44,50,57,65,78,80,94])
    valid = [train.pop(i) for i in valid_idxs]
    print('Data separated into train/valid.')
    return train, valid


## Perform all preprocessing at once

def read_and_preprocess_data():
    """Read, standardize and split data.
    """
    data = read_all_data()
    data = standardize_data(data)
    return split_train_valid(data)




data = read_all_data()

Reading data... Data read. There are 1 series in total.

In [13]:
x,y = data[0]

In [14]:
x.head()

,Fp1,Fp2,F7,F3,Fz,F4,F8,FC5,FC1,FC2,...,P7,P3,Pz,P4,P8,PO9,O1,Oz,O2,PO10
id,,,,,,,,,,,,,,,,,,,,,
subj1_series1_0,-31,363,211,121,211,15,717,279,35,158,...,536,348,383,105,607,289,459,173,120,704
subj1_series1_1,-29,342,216,123,222,200,595,329,43,166,...,529,327,369,78,613,248,409,141,83,737
subj1_series1_2,-172,278,105,93,222,511,471,280,12,177,...,511,319,355,66,606,320,440,141,62,677
subj1_series1_3,-272,263,-52,99,208,511,428,261,27,180,...,521,336,356,71,568,339,437,139,58,592
subj1_series1_4,-265,213,-67,99,155,380,476,353,32,165,...,550,324,346,76,547,343,446,171,67,581